### ISSUE TITLE
Videos not working

### ISSUE THREAD

**Issue by Makogan** [3ximus/aerial-sddm-theme#4]
This theme is amazing and beautiful, however I moved 4 videos into:
/usr/shar/sddm/themes/areial-sddm-themes/videos
Ran find <path-to-your-directory> -maxdepth 1 -type f > <playlist-file> using absolute paths for both night and day (i.e same playlist for both)

But all I get is the jgg image in the background, not the videos

**Comment by 3ximus** [comment]
I don't know if I understand your problem correctly. Did you ran the find command just like that? Because you've got to specify the directory in which to look for. If you've got the videos set up correctly in the playlist files i.e. they contain the video paths, then try running `sddm-greeter --theme <path-to-the-theme>` and show me the output of that

**Comment by Makogan** [comment]
Ok so as a preamble, when I boot up your theme shows up as expected and I can login just fine. The issue is that the theme is not showing videos, just the default background.png image. 

Currently I ran generate_playlist.sh to test things out so the m3u files are the ones generated by the script

In terms of testing I am inside of an xfce4 desktop environment when I run the command:

sddm-greeter --theme /usr/share/sdd/themes/aerial-sddm-theme

Which launches a window containing the log in screen (i.e a mockup so that I don't have to reboot every time to test things)

The output would be multiple iterations of:

GREETER: GStreamer "No URI handler implemented for <insert video url here>" 

(sorry about that I cannot copy paste right now, I am fidgeting around with hardware and my mouse is not working currently)

If I instead run the exact same command but after generating the playlists no error is written to the terminal, but the videos are not played

**Comment by 3ximus** [comment]
Did you install all the dependencies I mentioned? For that you should need `gst-plugins-good` (for arch linux) , if that doesn't work try the other Gstreamer plugin packages, I dont have any videos on my computer right now and im unable to get them on this connection... If it does not work I'll try to reproduced this when I'm able and get back to you

**Comment by Makogan** [comment]
I did install those dependencies, and it does not work with custom videos nor the script generated m3u files

**Comment by Makogan** [comment]
Ok so I installed the theme in my desktop and it works there, so i am not sure what's going on

**Comment by Makogan** [comment]
One last thing, when the video transisitons there is like 2 frames where it displays the background image, and it looks kind of weird. I have no experience with qt so I don't know how to add a smoother transition between videos, do you have a suggestion of where to look to add such an effect (I know how to program I just haven't use qt until now)

**Comment by 3ximus** [comment]
Try reinstalling gstreamer, I also don't know what might be the issue. Did you try the other plugin packages for it?

About video transitions. I don't like them either and have no idea how to make them smoother. I don't know Qt that much either, but I will look into it and see if i can fade between the videos but it will take a while because I don't have a decent internet connection right now.

I did most of the stuff by reading the QML reference manual. If you want you can look up the manual for *MediaPlayer*. It may have something about video transitions.

**Comment by 3ximus** [comment]
I added a fading transition to the videos. When one ends it fades to the next one. This requires you to be able to stream 2 videos at once (per screen) during the transition.
The default settings are: 
- It starts preloading the 2nd video 10 seconds before the current stops (to give time for it to start playing)
- Fading happens 3 seconds before the video stops

This gives 7 seconds for the 2nd video to load, if it doesn't it will fade to background image. From my testing this is enough time.
I didn't add these transitions on mouse click events because i think its unecessary and i only added that feature before for testing purposes...

**Comment by Makogan** [comment]
Awesome!
I wanted to help, but... I got tangled doing my own things. Glad you fixed it though.

**Comment by 3ximus** [comment]
No problem, it took forever for me to get around to it too xD
Thanks for the feedback on this!
